pipeline {
    agent {
        docker {
            image 'node:18'
            args '-u root:root'
        }
    }

    environment {
        FIREBASE_TOKEN = credentials('FIREBASE_TOKEN')
    }

    options {
        skipDefaultCheckout()
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Mokhaled2004/jenkins.git'
            }
        }

        stage('Install Firebase CLI') {
            steps {
                sh 'npm install -g firebase-tools'
                sh 'firebase --version'
            }
        }

        stage('Authenticate Firebase') {
            steps {
                sh 'firebase logout || true'
                sh 'firebase login:ci --token "$FIREBASE_TOKEN"'
            }
        }

        stage('Deploy to Firebase Hosting') {
            steps {
                sh 'firebase deploy --only hosting --force --debug --token "$FIREBASE_TOKEN"'
            }
        }
    }

    post {
        success {
            echo "🔥 Deploy success!"
        }
        failure {
            echo "💀 Deploy failed!"
        }
    }
}
