pipeline {
    agent {
        docker {
            image 'node:18'
            args '-u root:root'
        }
    }

    environment {
        FIREBASE_TOKEN = credentials('FIREBASE_TOKEN')
    }

    stages {
        stage('Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('Install Firebase Tools') {
            steps {
                sh 'npm install -g firebase-tools'
            }
        }

        stage('Deploy to Firebase') {
            steps {
                sh 'ls -la'          // debug: show files in workspace
                sh 'pwd'             // debug: show current dir
                sh 'npx firebase deploy --only hosting --force --debug'
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful!"
        }
        failure {
            echo "❌ Deployment failed. Check logs!"
        }
    }
}
