pipeline {
    agent {
        docker {
            image 'node:18'
            args '-u root:root'
        }
    }

    environment {
        FIREBASE_TOKEN = credentials('FIREBASE_TOKEN')
    }

    options {
        timestamps()
    }

    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Repo') {
            steps {
                dir('firebase-app') { // checkout into a dedicated folder
                    checkout scm
                }
            }
        }

        stage('Install Firebase Tools') {
            steps {
                sh '''
                npm install -g firebase-tools
                '''
            }
        }

        stage('Deploy to Firebase Hosting') {
            steps {
                dir('firebase-app') {
                    sh '''
                    echo "Deploying to Firebase..."
                    npx firebase deploy --only hosting --force --debug
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful!"
        }
        failure {
            echo "❌ Deployment failed. Check logs!"
        }
    }
}
